web/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',
                 __name__,
                 template_folder='../templates/main',
                 static_folder='../static')

from . import views, errors

web/app/main/views.py
from flask import render_template, request, abort, session, redirect, url_for
from . import main
from .use_cases import RetrieveCourseCatalog, RetrieveCourseCatalogCommand
from .use_cases import RetrieveCourseData, RetrieveCourseDataCommand
from .use_cases import PlaceAnInfoRequest, PlaceAnInfoRequestCommand
from .use_cases import RetrieveHomeRecommendations, RetrieveHomeRecommendationsCommand
from .use_cases import RetrieveCategories

users = [
    '1460318498c1f53bb880ce2e6d9ef64b',
    '001d7fed950bc1f5834b2d4af75b1879',
    '0000b20311e912f825aadd5bd195d9d4',
    '0105ce929e7d4832f945e2b500eb86e0',
    '016602affb282ed547501f8a8b9283ed'
]

test_password = 'testing'


@main.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        req = request.form

        user = req.get('user')
        password = req.get('password')

        if user not in users or password != test_password:
            error = 'Invalid Credentials. Please try again.'
        else:
            session.clear()
            session['user_id'] = user
            session['user_name'] = 'User {}'.format(users.index(user) + 1)

            return redirect(url_for('main.home'))

    return render_template('login.html', users=users, error=error)


@main.route('/logout')
def logout():
    session.pop('user_id', None)
    session.pop('user_name', None)

    return redirect(url_for('main.home'))


@main.route('/', methods=['GET'])
def home():
    command = RetrieveHomeRecommendationsCommand(user_id=session.get('user_id'))
    response = RetrieveHomeRecommendations.execute(command)

    return render_template('home.html',
                           recommendations=response['recommendations'],
                           categories=response['categories'])


@main.route('/categories', methods=['GET'])
def categories():
    response = RetrieveCategories.execute()

    return render_template('categories.html', response=response)


@main.route('/catalog', methods=['GET'])
def catalog():
    command = RetrieveCourseCatalogCommand(page=request.args.get('page', default=1),
                                           sort_by=request.args.get('sort_by', default='leads'),
                                           category=request.args.get('category'))

    response = RetrieveCourseCatalog.execute(command)

    return render_template('course-catalog.html', response=response)


@main.route('/course/<int:course_id>', methods=['GET'])
def course(course_id):
    command = RetrieveCourseDataCommand(course_id, session.get('user_id'))

    response = RetrieveCourseData.execute(command)

    return render_template('course.html',
                           course=response['course'],
                           recommendations=response['recommendations'])


@main.route('/request-information', methods=['POST'])
def request_information():
    email = request.form.get('email')
    course_id = request.form.get('courseId')

    command = PlaceAnInfoRequestCommand(course_id, email)
    response = PlaceAnInfoRequest.execute(command)

    if not response['success']:
        return abort(500)

    return render_template('request-information.html', response=response)

web/app/templates/main/categories.html
{% extends "base.html" %}
{% block title %}Categories{% endblock %}
{% block content %}
<div class="col-md-12">
    <h1>Categories</h1>
    <div class="row mt-3">
        {% for category_id, category in response.categories.items() %}
        <div class="col-md-3">
            <a href="{{ url_for('main.catalog', category=category_id )}}">{{ category.name }}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

web/app/templates/main/category-meta.html
<br>
<span class="category-meta">
    <i class="fa fa-star fa-2 {{ 'star-rating' if category.weighted_rating else 'star-rating-none' }}" aria-hidden="true"></i> <span class="small rating">{{'%0.2f' % category.weighted_rating|float}}</span>
    <span class="badge badge-pill badge-light">{{ category.number_of_leads }} {% if category.number_of_leads != 1 %}requests{% else %}request{% endif %}</span>
</span>

web/app/templates/main/course-catalog.html
{% if response.category_id %}
{% set cat_qstring = '&category=' + response.category_id|string %}
{% else %}
{% set cat_qstring = '' %}
{% endif %}

{% if response.category_name %}
{% set selected_category = response.category_name %}
{% else %}
{% set selected_category = 'All categories' %}
{% endif %}

{% extends "base.html" %}
{% block title %}Catalog | {{ selected_category }}{% endblock %}
{% block content %}
<div class="col-md-12">
    <h1>{{ selected_category }}</h1>
</div>
<div class="col-md-3 left-sidebar">
    <div class="card">
        <div class="card-body p-0">
            <h5 class="card-title p-2">Sort by</h5>
            <div class="px-3 py-2">
                <a href="{{ url_for('main.catalog', sort_by='leads')}}{{cat_qstring}}" class="btn btn-block btn-sm {{ 'btn-dark disabled' if response.sort_by == 'leads' else 'btn-outline-dark' }}">Number of leads</a>
                <a href="{{ url_for('main.catalog', sort_by='rating')}}{{cat_qstring}}" class="btn btn-block btn-sm {{ 'btn-dark disabled' if response.sort_by == 'rating' else 'btn-outline-dark' }}">Rating</a>
            </div>
            <h5 class="card-title p-2">Categories</h5>
            <div class="list-group list-group-flush categories-menu">
                <a href="{{ url_for('main.catalog', sort_by=response.sort_by)}}" class="list-group-item list-group-item-action{{ '' if response.category_id else ' active' }}">All categories</a>
                {% for category_id, category in response.categories.items() %}
                    <a href="{{ url_for('main.catalog', sort_by=response.sort_by, category=category_id)}}" class="list-group-item list-group-item-action{{ ' active' if category_id ==  response.category_id else '' }}">
                        {{category.name}}
                        {% include 'main/category-meta.html' %}
                    </a>
                {% endfor %}
                <a href="{{ url_for('main.categories')}}" class="list-group-item list-group-item-action text-center">
                    More categories&hellip;
                </a>
            </div>
        </div>
    </div>
</div>
<div class="col-md-9">
    {% for course_id, course in response.courses.items() %}
    <div class="col-xs-12 clearfix course-list-item border rounded">
        <h3><a href="{{ url_for('main.course', course_id=course_id) }}">{{ course.title }}</a></h3>
        {% include 'main/course-meta.html' %}
        <p class="course-description">
            {% if course.description %}
            {{ course.description|truncate(250) }}
            {% endif %}
        </p>
        <p><button type="button" class="btn btn-primary float-right request-info-btn" data-course-id="{{ course_id }}" data-toggle="modal" data-target="#requestInfoModal">Request information</button></p>
    </div>
    {% endfor %}

    <nav aria-label="paginator">
        <ul class="pagination justify-content-center">
            <li class="page-item{{ '' if response.prev_page else ' disabled' }}">
                <a class="page-link" href="{{ url_for('main.catalog', sort_by=response.sort_by, page=response.prev_page) }}{{cat_qstring}}" tabindex="-1">Previous</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">{{response.current_page}} of {{response.total_pages}} pages</a>
            </li>
            <li class="page-item{{ '' if response.next_page else ' disabled' }}">
                <a class="page-link" href="{{ url_for('main.catalog', sort_by=response.sort_by, page=response.next_page) }}{{cat_qstring}}">Next</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/request-info.js') }}"></script>
{% endblock %}

{% include 'main/request-form.html' %}

web/app/templates/main/course-list.html
{% if courses|length %}
<div class="card-body px-0 py-0">
    <ul class="list-group list-group-flush">
        {% for course_id, course in courses.items() %}
        <li class="list-group-item">
            <a href="{{ url_for('main.course', course_id=course_id) }}">{{course.title}}</a><br>
            <span class="lead small">{{ course.center }} | {{ course.category_name }}</span><br>
            <i class="fa fa-star fa-1 {{ 'star-rating' if course.weighted_rating else 'star-rating-none' }}" aria-hidden="true"></i> <span class="small">{{'%0.2f' % course.weighted_rating|float}} ({{course.number_of_reviews}})</span>
            <span class="badge badge-pill badge-light">{{course.number_of_leads}} {% if course.number_of_leads != 1 %}requests{% else %}request{% endif %}</span>
            <i class="fa fa-info-circle fa-1 text-primary request-info-btn request-info-mini" data-course-id="{{ course_id }}" data-toggle="modal" data-target="#requestInfoModal" title="Request Information"></i>
        </li>
        {% endfor %}
    </ul>
</div>
{% else %}
<div class="card-body">
    <div class="alert alert-warning">
        <i class="far fa-surprise fa-2x"></i> Ups! No recommendations available
    </div>
</div>
{% endif %}

web/app/templates/main/course-meta.html
<h4>{{course.center}} | <span class="small lead">{{ course.category_name }}</span></h4>
<p class="course-meta">
    <i class="fa fa-star fa-2 {{ 'star-rating' if course.weighted_rating else 'star-rating-none' }}" aria-hidden="true"></i> <span class="small">{{'%0.2f' % course.weighted_rating|float}} Based on {{ course.number_of_reviews }} {% if course.number_of_reviews != 1 %}reviews{% else %}review{% endif %}</span>
    <span class="badge badge-pill badge-light">{{course.number_of_leads}} {% if course.number_of_leads != 1 %}requests{% else %}request{% endif %}</span>
</p>

web/app/templates/main/course.html
{% extends "base.html" %}
{% block title %}{{course.title}}{% endblock %}
{% block content %}
<div class="col-md-12">
    <h1>{{course.title}}</h1>
    <hr>
    {% include 'main/course-meta.html' %}
    <div class="row">
        <div class="col-md-10 border-right">
            <p>
                {% if course.description %}
                {{course.description}}
                {% else %}
                    <div class="alert alert-warning" role="alert">
                        This course has no description
                    </div>
                {% endif %}
            </p>
        </div>
        <div class="col-md-2 pt-1">
            <p><button type="button" class="btn btn-primary request-info-btn" data-course-id="{{course.id}}" data-toggle="modal" data-target="#requestInfoModal">Request information</button></p>
        </div>
    </div>
</div>

{% include 'main/recommendations.html' %}

{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/request-info.js') }}"></script>
{% endblock %}

{% include 'main/request-form.html' %}

web/app/templates/main/home.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-12">
    {% if recommendations.by_user|length %}
        <h3 class="py-3">Recommendations for {{ session['user_name'] }}</h3>
        <h5 class="py-3">Because you were interested in</h5>
        <ul>
            {% for course_id, course in recommendations.user_courses.items() %}
            <li><a href="{{ url_for('main.course', course_id=course_id) }}">{{ course.title }}</a></li>
            {% endfor %}
        </ul>
        {% with courses=recommendations.by_user %}
            {% include 'main/course-list.html' %}
        {% endwith %}
    {% endif %}
    <h3 class="py-3">Our Top Courses</h3>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    The Most Often Requested
                </div>
                {% with courses=recommendations.by_number_of_leads %}
                    {% include 'main/course-list.html' %}
                {% endwith %}
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Top Rated
                </div>
                {% with courses=recommendations.by_rating %}
                    {% include 'main/course-list.html' %}
                {% endwith %}
            </div>
        </div>
    </div>
    <h3 class="py-3">Popular Categories</h3>
    <div class="row px-3 popular-categories">
        {% for category_id, category in categories.items() %}
        <a class="w-25 mr-2 mb-2 p-3 border text-center" href="{{ url_for('main.catalog', category=category_id) }}">
            {{ category.name }}
            {% include 'main/category-meta.html' %}
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

web/app/templates/main/login.html
{% extends "base.html" %}
{% block title %}Sign-in{% endblock %}
{% block styles %}
<link href="{{ url_for('static', filename='css/themes/courses-recommender/signin.css') }}" rel="stylesheet">
{% endblock %}
{% block navbar %}{% endblock %}
{% block content %}
<div class="text-center w-100">
    {% if error %}
    <div class="alert alert-danger"><strong>Error:</strong> {{ error }}</div>
    {% endif %}
    <form class="form-signin" method="post">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <div class="form-group">
            <label for="user" class="sr-only">User</label>
            <select class="form-control" id="user" name="user">
                <option>Select User</option>
                {% for user in users %}
                <option value="{{user}}">User {{loop.index}}</option>
                {% endfor %}
            </select>
        </div>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; Courses Recommendations 2019-2020</p>
    </form>
</div>
{% endblock %}
{% block footer %}{% endblock %}

web/app/templates/main/recommendations.html
<div class="col-md-12">
    {% if recommendations.by_leads|length %}
        <h3 class="py-3">Users who requested information about this course were also interested in</h3>
        <div class="card">
            {% with courses=recommendations.by_leads %}
            {% include 'main/course-list.html' %}
            {% endwith %}
        </div>
    {% endif %}

    <h3 class="py-3">You may also be interested in</h3>
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    The Most Often Requested in {{ course.category_name }}
                </div>
                {% with courses=recommendations.by_number_of_leads %}
                {% include 'main/course-list.html' %}
                {% endwith %}
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Top Rated in {{ course.category_name }}
                </div>
                {% with courses=recommendations.by_rating %}
                {% include 'main/course-list.html' %}
                {% endwith %}
            </div>
        </div>
        <div class="col-md-4 recommendations-list-col">
            <div class="card">
                <div class="card-header">
                    Similar Courses
                </div>
                {% with courses=recommendations.by_content %}
                {% include 'main/course-list.html' %}
                {% endwith %}
            </div>
        </div>
    </div>
    {% if recommendations.by_user|length %}
    <h3 class="py-3">Recommendations for {{ session['user_name'] }}</h3>
    <h4 class="py-3">Maybe you would be interested in these courses</h4>
    <div class="card">
        {% with courses=recommendations.by_user %}
        {% include 'main/course-list.html' %}
        {% endwith %}
    </div>
    {% endif %}
</div>

web/app/templates/main/request-form.html
<div class="modal fade" id="requestInfoModal" tabindex="-1" role="dialog" aria-labelledby="requestInfoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="requestInfoModalLabel">Request Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" action="/request-information">
                <input type="hidden" name="courseId" id="courseId"/>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

web/app/templates/main/request-information.html
{% extends "base.html" %}
{% block title %}{{response.course_title}}{% endblock %}
{% block content %}
<div class="col-md-12">
    <div class="alert alert-success col-md-12" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="alert-heading">Your request has been sent successfully!</h4>
        <p>You will receive a response shortly</p>
    </div>
    <h4>Users who requested information about "{{response.course_title}}" were also interested in ...</h4>
    <div class="row">
        {% with courses = response.recommendations.by_leads %}
            {% include 'main/course-list.html' %}
        {% endwith %}
    </div>
</div>
{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/request-info.js') }}"></script>
{% endblock %}

{% include 'main/request-form.html' %}